export const FEATURE_MARKERS = {
  "open-targets": {
    requiredMarkers: [
      "linux:{label:`Dolphin`",
      "codex-dolphin-file-manager",
      "process.env.CODEX_DOLPHIN_BIN?.trim()",
      "e?e.includes(`/`)?(0,h.existsSync)(e):Os(e):Os(`dolphin`)",
      "open:async({command:e,path:t})=>{await Ns(e,[t])}",
      "codexLinuxGwenviewTarget",
      "codexLinuxTyporaTarget",
      "codexLinuxWpsTarget",
      "codexLinuxOfficeRemoteAppTarget",
      "function codexLinuxDefaultAppIconForPath",
      "function codexLinuxOfficeKind",
      "function codexLinuxRemoteAppName",
      "codexLinuxClionTarget",
      "function codexLinuxJetBrainsArgs",
      "args:codexLinuxJetBrainsArgs",
      "linux:{label:`VS Code`",
      "linux:{label:`PyCharm`",
      "linux:{label:`WebStorm`",
      "linux:{label:`CLion`",
    ],
    forbiddenMarkers: [
      "codexLinuxKittyTarget",
      "codexLinuxClaudeCodeTarget",
      "codexLinuxZedTarget",
      "codexLinuxIntellijTarget",
      "codexLinuxRiderTarget",
      "codexLinuxRustroverTarget",
      "codexLinuxWpsWriterTarget",
      "codexLinuxWpsSpreadsheetsTarget",
      "codexLinuxWpsPresentationTarget",
      "codexLinuxWpsPdfTarget",
      "WPS Writer",
      "WPS Spreadsheets",
      "WPS Presentation",
      "WPS PDF",
      "detect:()=>po(`",
      "detect:()=>Fi(`",
      "detect:()=>fm(`",
      "ls(`gdbus`)?(0,s.join)(process.resourcesPath,`codex-dolphin-file-manager`):null",
      "K7(`gdbus`)?(0,E.join)(process.resourcesPath,`codex-dolphin-file-manager`):null",
      "org.freedesktop.FileManager1.ShowFolders",
      "org.freedesktop.FileManager1.ShowItems",
      "open:async({command:e,path:t})=>{let n=IM(t);if(n&&(0,u.statSync)(n).isFile()){await ps(e,[`--select`,n]);return}await ps(e,[n??t])}",
      "open:async({command:e,path:t})=>{let n=IM(t);if(n&&(0,u.statSync)(n).isFile()){await ps(e,[`--new-window`,`--select`,n]);return}await ps(e,[`--new-window`,n??t])}",
    ],
  },
  "generated-output-artifacts": {
    requiredMarkers: {
      webviewGeneratedOutputArtifacts: [
        "function codexLinuxIsGeneratedImageTempArtifactPath(e)",
        "function codexLinuxResolveGeneratedImageArtifactPath(e,t)",
        "codexLinuxGeneratedImageSources=[]",
        "for(let e of a.items)e?.type===`imageGeneration`&&e.src!=null&&ui(e.src)&&codexLinuxGeneratedImageSources.push(e.src)",
        "let n=codexLinuxResolveGeneratedImageArtifactPath(e.path,codexLinuxGeneratedImageSources)",
      ],
    },
    forbiddenMarkers: {
      webviewGeneratedOutputArtifacts: [
        "a.push([...c,...Ym(s,r,n)])",
        "case`file`:l({type:`file`,path:t==null?e.path:pt(t,e.path)});break",
      ],
    },
  },
  "browser-use": {
    requiredMarkers: [
      "CODEX_ELECTRON_ENABLE_LINUX_BROWSER_USE",
      "browserPane:!0,inAppBrowserUse:!0,inAppBrowserUseAllowed:!0,externalBrowserUse:!0,externalBrowserUseAllowed:!0",
    ],
    forbiddenMarkers: [
      "function Xe(e,{buildFlavor:t=i.a.resolve(),env:n=g.default.env,platform:r=g.default.platform}={}){let a=r===`win32`&&e.computerUse===!0?{...e,computerUseNodeRepl:!0}:e,o=r===`win32`&&n.CODEX_ELECTRON_ENABLE_WINDOWS_COMPUTER_USE===`1`?{...a,computerUse:!0,computerUseNodeRepl:!0}:a,s=t===i.a.Dev?Ze(n):null;return s==null?{...o,deviceAttestation:be({platform:r})}:{...o,...s,deviceAttestation:be({platform:r})}}",
    ],
  },
  "browser-storage-identity": {
    requiredMarkers: [
      "codexLinuxBrowserStorageId",
      "this.codexLinuxBrowserStorageId",
      /getPagePersistence\([^)]*\)\{[\s\S]*?mode:`persistent`/,
      /getPagePersistence\([^)]*\)\{[\s\S]*?this\.codexLinuxBrowserStorageId\([^)]*\)[\s\S]*?mode:`persistent`/,
    ],
    forbiddenMarkers: [
      /getBrowserStorageId\([\s\S]*?crypto\.randomUUID\(\)[\s\S]*?mode:`ephemeral`[\s\S]*?getExistingBrowserStorageId/,
      /getPagePersistence\([\s\S]*?crypto\.randomUUID\(\)[\s\S]*?mode:`persistent`/,
    ],
  },
  "browser-session-routing": {
    requiredMarkers: {
      main: [
        "function AP(e){let t=e[OP]??e[`data-conversation-id`]??null,r=e[kP]??null;if(typeof t==`string`&&t.length>0)return{browserTabId:typeof r==`string`&&r.length>0?n.Mc(r):NP(t),conversationId:t};let i=MP(e.partition);if(i==null||!i.startsWith(`persist:codex-browser-app-route:`))return null;try{let e=decodeURIComponent(i.slice(n.es.length));if(e.length===0)return null;let[t,r]=e.split(`\\0`);return t==null||t.length===0?null:{browserTabId:r==null||r.length===0?NP(t):n.Mc(r),conversationId:t}}catch{return null}}",
        "function jP(e){let t=e.partition;if(typeof t!=`string`)return null;let r=t.lastIndexOf(n.$o);if(r===-1)return null;let i=t.slice(r+n.$o.length),a=i.lastIndexOf(`:`);if(a===-1)return null;let o=i.slice(0,a),s=Number(i.slice(a+1));return o.length===0||!Number.isInteger(s)||s<=0?null:{hostGeneration:s,rendererInstanceId:o}}",
        "function OL({configureBrowserSession:e,params:t,preloadPath:n,webPreferences:r}){t.partition=oS(`app`),r.session=e(),r.preload=n,AL(t,r)}",
      ],
      webviewCoreSource: [
        "function _x(e,t){return`${yx}${encodeURIComponent(`${e}\\0${t}`)}`}",
        "function vx(e,t,n,r){return`${_x(e,t)}${bx}${n}:${r}`}",
        "yx=`persist:codex-browser-app-route:`",
        "bx=`:host:`",
      ],
      webviewBrowserSidebarRuntime: [
        "setAttribute(`partition`",
      ],
    },
    forbiddenMarkers: {
      main: [
        "codexLinuxBrowserRouteIdentity",
        "codexLinuxBrowserHostIdentity",
      ],
      webviewCoreSource: [
        "function codexLinuxBrowserPartition()",
      ],
      webviewBrowserSidebarRuntime: [
        "data-browser-sidebar-renderer-instance-id",
        "data-browser-sidebar-host-generation",
      ],
    },
  },
  "browser-automation-runtime-name": {
    requiredMarkers: {
      main: [
        "CODEX_BROWSER_AUTOMATION_PATH",
        "browserAutomationPath",
        "browser_automation",
        "browser-automation-active-execs-kill",
      ],
      worker: [
        "browserAutomationPath",
        "browser_automation",
        "browserAutomation.write",
      ],
      buildBrowserRuntimeSource: [
        "browserAutomationPath",
        "browser_automation",
        "browserAutomation.write",
        "BROWSER_AUTOMATION_NODE_PATH",
      ],
      buildChromeNativeHostSource: [
        "browserAutomationPath",
        "browser_automation",
      ],
      webviewCoreSource: [
        "browserAutomationPath",
        "browser_automation",
        "browserAutomation.write",
        "Do not run ad hoc browser_automation browser-client path discovery.",
        "Run a browser_automation JavaScript snippet",
      ],
      webviewAppServerManagerSignals: [
        "browser-automation-active-execs-kill",
        "browser_automation",
      ],
      webviewDebugModal: [
        "browser_automation",
      ],
      webviewLocalConversationThread: [
        /[$A-Z_a-z][$\w]*\.server===`browser_automation`/,
      ],
      webviewSplitItemsIntoRenderGroups: [
        "e.invocation.server===`browser_automation`",
      ],
    },
    forbiddenMarkers: {
      main: [
        "CODEX_NODE_REPL_PATH",
        "nodeReplPath",
        "nodeReplPathSource",
        "node_repl",
        "node-repl-active-execs-kill",
      ],
      worker: [
        "nodeReplPath",
        "node_repl",
        "nodeRepl.write",
      ],
      buildBrowserRuntimeSource: [
        "nodeReplPath",
        "node_repl",
        "nodeRepl.write",
        "NODE_REPL_NODE_PATH",
      ],
      buildChromeNativeHostSource: [
        "nodeReplPath",
        "node_repl",
      ],
      webviewCoreSource: [
        "nodeReplPath",
        "node_repl",
        "nodeRepl.write",
        "Do not run ad hoc node_repl browser-client path discovery.",
        "Run a node_repl JavaScript snippet",
      ],
      webviewAppServerManagerSignals: [
        "node_repl",
      ],
      webviewDebugModal: [
        "node_repl",
        "Node REPL",
      ],
      webviewLocalConversationThread: [
        "node_repl",
      ],
      webviewSplitItemsIntoRenderGroups: [
        "e.invocation.server===`node_repl`",
      ],
    },
  },
  "chrome-native-host-staging": {
    requiredMarkers: {
      buildChromeNativeHostSource: [
        "codexLinuxChromePluginRoot",
        /pluginName:[$A-Z_a-z][$\w]*\.pluginName/,
        /pluginRoot:codexLinuxChromePluginRoot,target:/,
        /browserClientPath:\(0,[$A-Z_a-z][$\w]*\.join\)\(codexLinuxChromePluginRoot,`scripts`,`browser-client\.mjs`\)/,
      ],
    },
    forbiddenMarkers: {
      buildChromeNativeHostSource: [
        /pluginRoot:[$A-Z_a-z][$\w]*\.pluginRoot,target:/,
        /browserClientPath:\(0,[$A-Z_a-z][$\w]*\.join\)\([$A-Z_a-z][$\w]*\.pluginRoot,`scripts`,`browser-client\.mjs`\)/,
      ],
    },
  },
  "computer-use-provider": {
    requiredMarkers: {
      webviewComputerUseSettings: [
        "K([..._.availablePlugins,..._.installedPlugins],fn,v)",
      ],
      webviewComputerUseProviderSettings: [
        "kde-computer-use",
        "t===`computer-use`",
        "plugin.name===`kde-computer-use`",
        "marketplaceName===`local`",
      ],
    },
    forbiddenMarkers: {
      webviewComputerUseSettings: [
        "K(_.availablePlugins,fn,v)",
        "function codexLinuxComputerUseProvider()",
      ],
      webviewComputerUseProviderSettings: [
        "function Oi(e,t,n){let r=e.filter(e=>e.plugin.name===t||e.plugin.id.split(`@`)[0]===t),i=y(Pt());return(i==null?void 0:r.find(e=>e.marketplaceName===i))??r.find(e=>re(e.marketplaceName))??r.find(e=>e.marketplaceName===`openai-curated`)??r.find(e=>Wt(n,e.marketplacePath))??null}",
      ],
    },
  },
  "computer-use-availability": {
    requiredMarkers: {
      webviewPluginFeatureGate: [
        /function [A-Za-z_$][\w$]*\(([A-Za-z_$][\w$]*)\)\{return \1===`macOS`\|\|\1===`windows`\|\|\1===`linux`\}/,
        /isComputerUseGateEnabled:[A-Za-z_$][\w$]*\|\|[A-Za-z_$][\w$]*===`linux`/,
        /isHostCompatiblePlatform:[A-Za-z_$][\w$]*\([A-Za-z_$][\w$]*\)/,
      ],
    },
    forbiddenMarkers: {
      webviewPluginFeatureGate: [
        /function [A-Za-z_$][\w$]*\(([A-Za-z_$][\w$]*)\)\{return \1===`macOS`\|\|\1===`windows`\}/,
        /isComputerUseGateEnabled:[A-Za-z_$][\w$]*,isHostCompatiblePlatform:[A-Za-z_$][\w$]*\([A-Za-z_$][\w$]*\),isPlatformLoading:[A-Za-z_$][\w$]*,windowType:`electron`/,
      ],
    },
  },
  "browser-backend-registry": {
    requiredMarkers: [
      "codexLinuxRegisterBrowserBackend",
      "codexLinuxBrowserRegistryPath",
      "codexLinuxPruneBrowserRegistry",
      "codexLinuxNormalizeBrowserBackend",
      "codex-electron-iab",
      "codex-browser-backends-",
    ],
    forbiddenMarkers: [],
  },
  "browser-profile-import": {
    requiredMarkers: {
      main: [
        "codex-linux-browser-profile-import.cjs",
        "createLinuxBrowserProfileImporter({electron:c})",
        "process.platform===`linux`",
      ],
      buildBrowserRuntimeSource: ["G([`atlas`,`chrome`,`onepassword`])"],
      webviewCoreSource: ["V([`atlas`,`chrome`,`onepassword`])"],
      webviewBrowserProfileImportDialog: [
        "document.documentElement.dataset.codexOs===`darwin`&&k?.source!==`onepassword`",
        "case`onepassword`:{r=(0,$.jsx)(ge,{className:`size-4 shrink-0`})",
        "No Chrome, Atlas, or 1Password profiles were found on this device",
        "Import from your browser",
        "Choose data to bring over to the built-in browser",
      ],
      webviewComputerUseProviderSettings: [
        "Developer mode",
        "Enable full CDP access",
        "full Chrome DevTools Protocol (CDP) access",
      ],
    },
    forbiddenMarkers: {
      main: [
        "function mS(){if(process.platform!==`darwin`&&process.platform!==`win32`||!i.o())return null;",
      ],
      buildBrowserRuntimeSource: ["G([`atlas`,`chrome`])"],
      webviewCoreSource: ["V([`atlas`,`chrome`])"],
      webviewBrowserProfileImportDialog: [
        "ee=typeof document<`u`&&document.documentElement.dataset.codexOs===`darwin`,N=M&&k?.source===`chrome`",
        "document.documentElement.dataset.codexOs===`darwin`||document.documentElement.dataset.codexOs===`linux`)&&k?.source!==`onepassword`",
        "No Chrome or Atlas profiles were found on this device",
      ],
      webviewComputerUseProviderSettings: [],
    },
  },
  "browser-security": {
    requiredMarkers: [
      "CODEX_DESKTOP_AUTH_FETCH_SOCKET",
      "CODEX_DESKTOP_BROWSER_APPROVAL_SOCKET",
      "codexLinuxStartBrowserSecurityServers",
      "codexLinuxCreateJsonSocketServer",
      "codexLinuxAuthenticatedFetch",
      "codexLinuxRequestBrowserApproval",
      "codexLinuxNormalizeBrowserApprovalRequest",
      "codexLinuxNormalizeBrowserApprovalOrigin",
      "codexLinuxReadBrowserUseState",
      "codexLinuxResolveBrowserApprovalPolicy",
      "sensitive_data===`browsing_history`",
      "file_transfer===`download`||t.file_transfer===`upload`",
      "createServer({allowHalfOpen:!0}",
      "Linux authenticated fetch URL is not allowlisted",
      "Linux browser approval request is not allowlisted",
      "codexLinuxStartBrowserSecurityServers({appServerClient:he.getAppServerClient(),codexHome:P.codexHome})",
    ],
    forbiddenMarkers: [
      "prodApiBaseUrl:r.prodApiBaseUrl,hostId:L});u.startLinuxBrowserSecurityServers?.();let d=new",
      "linux-browser-origin-approvals.json",
      "Linux browser-use state unavailable",
      "Linux browser-use approval persist failed",
      "return await ux(e)",
      "await hx(`allowed`,e.origin,n)",
      "await gx(e.transferKind,`allowed`,e.origin,n)",
      "return await hx(e)",
      "await bx(`allowed`,e.origin,n)",
      "await xx(e.transferKind,`allowed`,e.origin,n)",
    ],
  },
  "chrome-setup-url": {
    requiredMarkers: {
      webviewPluginAvailability: [
        /https:\/\/chromewebstore\.google\.com\/detail\/codex\/\$\{encodeURIComponent\([$A-Z_a-z][$\w]*\.trim\(\)\)\}/,
        /id:[$A-Z_a-z][$\w]*\.trim\(\),name:`ChatGPT for Chrome`,url:[$A-Z_a-z][$\w]*\([$A-Z_a-z][$\w]*\)/,
      ],
      webviewPluginDetail: [
        "openTarget:`external-browser`,source:`plugin_browser_extension_setup`",
      ],
    },
    forbiddenMarkers: {
      webviewPluginAvailability: [
        /[$A-Z_a-z][$\w]*=`https:\/\/chromewebstore\.google\.com\/detail\/codex\/`/,
        /id:[$A-Z_a-z][$\w]*,name:`ChatGPT for Chrome`,url:`\$\{[$A-Z_a-z][$\w]*\}\$\{[$A-Z_a-z][$\w]*\}`/,
      ],
      webviewPluginDetail: [
        /onClick:\(\)=>\{[$A-Z_a-z][$\w]*\.dispatchMessage\(`open-in-browser`,\{url:[$A-Z_a-z][$\w]*\.url\}\)\},children:\(0,[$A-Z_a-z][$\w]*\.jsx\)\([$A-Z_a-z][$\w]*,\{id:`plugins\.detail\.setup\.openBrowserExtension`/,
        /onClick:[$A-Z_a-z][$\w]*=>\{[$A-Z_a-z][$\w]*\(\{event:[$A-Z_a-z][$\w]*,href:[$A-Z_a-z][$\w]*\.url,initiator:`open_in_browser_bridge`,openTarget:`external-browser`\}\)\},children:\(0,[$A-Z_a-z][$\w]*\.jsx\)\([$A-Z_a-z][$\w]*,\{id:`plugins\.detail\.setup\.openBrowserExtension`/,
      ],
    },
  },
  "native-titlebar": {
    mainRequiredMarkers: [
      "codex_desktop:linux-titlebar-config",
      "codex_desktop:linux-titlebar-action",
      "codex_desktop:linux-titlebar-debug",
      "CODEX_LINUX_TITLEBAR_DEBUG",
      "linux-titlebar-debug.jsonl",
      "__codexCustomTitlebar",
      "let F=process.platform===`linux`?void 0:this.installApplicationMenuTitleBarOverlaySync",
      "n.__codexCustomTitlebar?this.windowZooms.set(n.id,t)",
      "process.platform!==`linux`&&!Dj()&&!I9(e)",
      "frame:!1,hasShadow:!0,transparent:!0,backgroundColor:`#00000000`,autoHideMenuBar:!0",
      "setMenu(null)",
      "setMenuBarVisibility(!1)",
      "BrowserWindow.getAllWindows().forEach",
      "process.platform===`linux`?c.Menu.setApplicationMenu(null):c.Menu.setApplicationMenu(It)",
    ],
    preloadRequiredMarkers: [
      "codex_desktop:linux-titlebar-config",
      "codex_desktop:linux-titlebar-action",
      "codex_desktop:linux-titlebar-debug",
      "linuxTitlebarConfigChannel",
      "linuxTitlebarActionChannel",
      "linuxTitlebarDebugChannel",
      "showApplicationMenu:process.platform===`linux`?void 0:async",
      "codex-linux-drag-style",
      "codex-linux-editor-input-style",
      "data-codex-linux-drag-root",
      ".composer-surface-chrome",
      ".ProseMirror",
      "[contenteditable]",
      '[role="textbox"]',
      "[data-codex-composer]",
      "[data-pierre-editor-surface]",
      "-webkit-user-select:text!important",
      "user-select:text!important",
      "cursor:text!important",
      "codex-linux-window-controls",
      "codexLinuxIpcRenderer",
      "codexLinuxIpcRenderer.invoke(linuxTitlebarConfigChannel)",
      "codexLinuxIpcRenderer.invoke(linuxTitlebarActionChannel",
      "CODEX_LINUX_TITLEBAR_DEBUG",
      "positionLinuxWindowControls",
      "resetLinuxWindowControlsPosition",
      "getLinuxTitlebarStartSlots",
      "linuxTitlebarReservedStartSlots",
      "querySelector(':scope > [data-test-id=\"header-shell-slot\"]')",
      "isLinuxImagePreviewOpen",
      "isLinuxSettingsSurface",
      "syncLinuxWindowControlsVisibility",
      "codexLinuxWindowControlsHidden",
      "data-codex-linux-window-controls-hidden",
      "--codex-linux-sidebar-glass-dark:rgba(14,14,16,.72)",
      "--codex-linux-sidebar-glass-light:color-mix(in srgb,var(--color-token-editor-background) 58%,transparent)",
      '[data-codex-window-type="electron"][data-codex-os="linux"].electron-dark .app-shell-left-panel',
      "backdrop-filter:blur(28px) saturate(1.25)",
      ".app-shell-left-panel:after{background:inherit!important;}",
      ".main-surface{border-top-left-radius:0!important;border-bottom-left-radius:0!important;border-start-start-radius:0!important;border-end-start-radius:0!important;}",
      "button:not(:disabled){opacity:1!important;filter:none!important;color:var(--color-token-text-primary)!important;}",
      "header-shell-slot",
      "app-shell-left-panel .app-header-tint{background:transparent!important",
      "linuxPointDebug",
      "pointSamples",
      'getComputedStyle(o,":after")',
      "background-color:transparent!important",
      '[role="dialog"][aria-label="Image preview"]',
      '[data-testid="image-preview-dismiss-area"]',
      'aria-hidden","true',
      "inert",
      'padding-left","80px',
      'top:16px;left:16px;height:14px',
      'width:14px;height:14px',
      'button:hover',
      'button:active',
      '[["close","Close"],["minimize","Minimize"],["maximize","Maximize"]]',
    ],
    mainForbiddenMarkers: [
      "case`quickChat`:case`primary`:return n===`darwin`?{titleBarStyle:`hiddenInset`,trafficLightPosition:A9(r),...e===`quickChat`?{hasShadow:!0,resizable:!0,transparent:!0}:{},...t?{}:{vibrancy:`menu`}}:n===`win32`||n===`linux`?{titleBarStyle:`hidden`,titleBarOverlay:j9(r),...e===`quickChat`?{resizable:!0}:{}}:{titleBarStyle:`default`,...e===`quickChat`?{resizable:!0}:{}};",
      "n===`linux`?{frame:!1,hasShadow:!0,transparent:!0,backgroundColor:`#00000000`}:{titleBarStyle:`default`};",
      "let F=this.installApplicationMenuTitleBarOverlaySync(M,o)",
      "setWindowZoom(e,t){let n=c.BrowserWindow.fromWebContents(e),r=n&&this.windowAppearances.get(n.id);n==null||r!==`primary`&&r!==`quickChat`||(process.platform===`darwin`?n.setWindowButtonPosition(A9(t)):(process.platform===`win32`||process.platform===`linux`)&&(this.windowZooms.set(n.id,t),n.setTitleBarOverlay(j9(t))))}",
      "shouldAlwaysUseOpaqueWindowSurface(e){return Wie({appearance:e,opaqueWindowsEnabled:this.isOpaqueWindowsEnabled(),platform:process.platform})||!Dj()&&!I9(e)}",
      "__codexCustomTitlebar=process.platform===`linux`&&o===`primary`;process.platform===`darwin`",
      "__codexCustomTitlebar&&M.setMenuBarVisibility(!1)",
      "c.Menu.setApplicationMenu(It),RX(_)",
    ],
    preloadForbiddenMarkers: [
      '[class~="group/windows-top-bar"]>*{visibility:hidden!important;opacity:0!important;}',
      "syncLinuxSidebarTopbar",
      "codex-linux-sidebar-top-surface",
      "--codex-linux-sidebar-top-surface-width",
      'group/windows-top-bar"]{width:var(--codex-linux-sidebar-top-surface-width)!important;',
      '.fixed>[data-test-id="header-shell-slot"]:first-child{visibility:hidden!important;opacity:0!important;}',
      'setProperty("clip-path","inset(0 0 0 "+i+"px)","important")',
      "codex-linux-header-tint-mask",
      "syncLinuxHeaderTintMask",
      "ensureLinuxHeaderTintMask",
      "getLinuxSidebarVisualRight",
      "getLinuxSidebarPanelRight",
      "--codex-linux-titlebar-glass-dark",
      "--codex-linux-titlebar-glass:",
      "var(--codex-linux-titlebar-glass",
      "codexLinuxHeaderTintMask",
      "codexLinuxSidebarHeaderClip",
      'app-shell-header-context-menu-surface"]{opacity:1!important;filter:none!important;color:var(--color-token-text-primary)!important;}',
      ':is(button,a,[role="button"],span,svg){opacity:1!important;filter:none!important;color:inherit!important;}',
      "sidebarHeaders",
      "ResizeObserver",
      "data-codex-linux-image-preview-open",
      "z-index:35;background:var(--color-token-editor-background)!important",
      '[data-codex-window-type="electron"][data-codex-os="linux"] .app-shell-left-panel{position:relative;z-index:35',
      "#codex-linux-header-tint-mask{position:fixed;pointer-events:none;z-index:29;background:var(--codex-titlebar-tint,transparent);-webkit-app-region:drag;}",
      'n.style.background=a?"transparent":"var(--codex-titlebar-tint,transparent)"',
      "--codex-linux-sidebar-surface",
      "color-mix(in srgb, var(--color-token-editor-background)",
      "syncLinuxLeftPanelTopInset",
      "--codex-linux-left-panel-padding-top",
      "background:var(--codex-linux-sidebar-surface)!important",
      'padding-right","96px',
      't.style.right="12px";t.style.left="auto"',
      'padding-left","96px',
      't.style.left="12px";t.style.right="auto"',
      '[["minimize","Minimize"],["maximize","Maximize"],["close","Close"]]',
      'document.querySelectorAll(\'.app-header-tint.draggable.pointer-events-none.fixed > [data-test-id="header-shell-slot"]:first-child\')',
      "showApplicationMenu:async(t,n,i)=>{await e.ipcRenderer.invoke(r,{menuId:t,x:n,y:i})}",
    ],
  },
  "settings-sidebar-surface": {
    requiredMarkers: {
      webviewSettingsPage: [
        "app-shell-left-panel window-fx-sidebar-surface relative flex min-h-0 shrink-0 flex-col overflow-hidden",
      ],
    },
    forbiddenMarkers: {
      webviewSettingsPage: [
        "app-shell-left-panel relative flex min-h-0 shrink-0 flex-col overflow-hidden",
      ],
    },
  },
  "settings-suggested-prompts": {
    requiredMarkers: {
      webviewGeneralSettings: [
        /\b[A-Za-z_$][\w$]*=!0/,
        "settings.agent.ambientSuggestions.rowLabel",
        "settings.agent.ambientSuggestions.toggleLabel",
        /if\(![A-Za-z_$][\w$]*\(\{authMethod:[A-Za-z_$][\w$]*,email:[A-Za-z_$][\w$]*\?\.[A-Za-z_$][\w$]*\?\?[A-Za-z_$][\w$]*,plan:[A-Za-z_$][\w$]*\?\.[A-Za-z_$][\w$]*\?\?[A-Za-z_$][\w$]*\}\)\)return null/,
      ],
      webviewAmbientSuggestionsEligibility: [
        /function [A-Za-z_$][\w$]*\(\{authMethod:[A-Za-z_$][\w$]*,email:[A-Za-z_$][\w$]*,plan:[A-Za-z_$][\w$]*\}\)\{return [A-Za-z_$][\w$]*===`apikey`\?!0:[A-Za-z_$][\w$]*===`chatgpt`\?/,
        /\b[A-Za-z_$][\w$]*=\[`plus`,`pro`,`prolite`,`business`,`team`,`self_serve_business_usage_based`\]/,
      ],
    },
    forbiddenMarkers: {
      webviewGeneralSettings: [
        /\b[A-Za-z_$][\w$]*=[A-Za-z_$][\w$]*\(`2425897452`\)/,
      ],
      webviewAmbientSuggestionsEligibility: [
        /\b[A-Za-z_$][\w$]*=\[`plus`,`pro`,`business`,`team`,`self_serve_business_usage_based`\]/,
      ],
    },
  },
};

export const RETIRED_LINUX_PATCH_MARKERS = {
  main: [
    "codexLinuxPreferredTargetCwd",
    /"set-preferred-app":async\(\{target:[$A-Z_a-z][$\w]*,cwd:codexLinuxPreferredTargetCwd\}\)=>\([$A-Z_a-z][$\w]*\(this\.getSettingsStore\(\),codexLinuxPreferredTargetCwd\?\?null,[$A-Z_a-z][$\w]*\),\{success:!0\}\)/,
    "codexLinuxWorkingSessionsStatusPath",
    "codexLinuxWriteWorkingSessionsStatus",
    "CODEX_WORKING_SESSIONS_STATUS_PATH",
    "working-sessions.json",
    /case`view-focused`:case`quit-app`:case`tray-menu-threads-changed`:codexLinuxWriteWorkingSessionsStatus\([$A-Z_a-z][$\w]*\);break;/,
    "codexLinuxWriteWorkingSessionsStatus({trayMenuThreads:{runningThreads:[]}},!1)",
  ],
  webviewFollowUp: [
    /var [$A-Z_a-z][$\w]*=\/\^::\(\?:inbox-item\|archive-thread\|code-comment\|git-stage\|git-commit\|git-create-branch\|git-push\|git-create-pr\|pr-auto-fix-progress\)\(\?=\$\|\[\\s\\\[\{\]\)\.\*\$\/gm;/,
    "case`imageGeneration`:{let e=typeof n.src==`string`?n.src.trim():``;if(e.length===0)break;a.push({type:`generated-image`,id:n.id,src:e,status:n.status});break}",
    "codexImageViewId",
    "app://fs/@fs${encodeURI(e).replaceAll",
    /case`imageView`:return typeof [$A-Z_a-z][$\w]*\.path==`string`&&[$A-Z_a-z][$\w]*\([$A-Z_a-z][$\w]*\.path\)!=null;/,
  ],
  webviewHtml: [
    "img-src &#39;self&#39; app: blob: data: http: https:;",
    "media-src &#39;self&#39; app: blob: data: http: https:;",
  ],
  webviewMarkdown: [
    "function codexLinuxNormalizeMarkdownRemoteMediaUrl(e)",
    "ke=codexLinuxNormalizeMarkdownRemoteMediaUrl(x)",
  ],
  webviewPluginAvailability: [
    "function codexLinuxPluginHasMcp",
    "function codexLinuxRestartAppServerForPluginMcp",
    "codexLinuxRestartAppServerForPluginMcp(f,t,D)",
  ],
};

export const START_SCRIPT_MARKERS = {
  requiredMarkers: [
    'export CODEX_CLI_PATH="${CODEX_CLI_PATH:-${CODEX_HOME:-$HOME/.codex}/packages/standalone/current/codex}"',
    '[ -x "$CODEX_CLI_PATH" ] || { echo "Error: CODEX_CLI_PATH is not executable: $CODEX_CLI_PATH" >&2; exit 1; }',
    'export CHROME_DESKTOP="${CHROME_DESKTOP:-Codex.desktop}"',
    'CODEX_DESKTOP_AUTH_FETCH_SOCKET',
    'CODEX_DESKTOP_BROWSER_APPROVAL_SOCKET',
    'CODEX_ELECTRON_ENABLE_LINUX_BROWSER_USE',
    'CODEX_BROWSER_USE_NODE_PATH',
    'CODEX_BROWSER_AUTOMATION_PATH',
    'exec "$SCRIPT_DIR/Codex" --no-sandbox "$@"',
  ],
  forbiddenMarkers: [
    "http.server 5175",
    "--disable-http-cache",
    "npm i -g @openai/codex",
    "codex-cli-wrapper",
    "app-server proxy",
    "codex_clean_daemon_env",
    "CODEX_LINUX_REMOTE_CONTROL_DAEMON",
    "app-server daemon",
    "remote-control start",
    "CODEX_STANDALONE_CLI_PATH",
    "CODEX_PATCHED_STANDALONE_CLI_PATH",
    "codex-standalone-patched",
    "curl -fsSL https://chatgpt.com/codex/install.sh | sh",
  ],
};
